%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/zed2/zed_node/imu/data"
image0_topic: "/zed2/zed_node/left/image_rect_gray"
image1_topic: "/zed2/zed_node/right/image_rect_gray"
output_path: "/home/ocean/vins_fusion/vins_output"

cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 1280
image_height: 720
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 7.2583436838884463e-03, 3.1262286184700061e-03,
       9.9996877108317339e-01, 2.7846771836535344e-02,
       -9.9997127021690468e-01, 2.2079589703867253e-03,
       7.2514590239382004e-03, -1.3445916236269959e-01,
       -2.1852202994935288e-03, -9.9999267577908324e-01,
       3.1421649276466290e-03, -1.5345938723694638e-01, 0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 5.6714720794935891e-03, 3.8397242791807784e-03,
       9.9997654518589141e-01, 3.9747151598222973e-02,
       -9.9998101902341729e-01, 2.4292859131085365e-03,
       5.6621694464449313e-03, -2.5326283453261172e-01,
       -2.4074877651626414e-03, -9.9998967749042889e-01,
       3.8534290246934333e-03, -1.5210664818110534e-01, 0., 0., 0., 1. ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 1.7512828345266122e-02 #0.04         # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 3.3502044635737617e-03 #0.004         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 4.2528647943077756e-04 #0.002         # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 4.8760608618583259e-05 #4.0e-5       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.8046         # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.002004                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 1        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/ocean/vins_fusion/vins_output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
