%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1  

#common parameters
imu_topic: "/imu0"
image0_topic: "/cam0/image_raw"
image1_topic: "/cam0/image_raw"
output_path: "/home/ocean/vins_fusion/vins_output"

cam0_calib: "cam0.yaml"
cam1_calib: "cam0.yaml"
image_width: 640
image_height: 360

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
# extrinsicRotation: !!opencv-matrix
#    rows: 3
#    cols: 3
#    dt: d
#    data: [-0.0015147, -0.99971458, 0.02384257,
#          -0.99999504, 0.00158013, 0.00272574, 
#          -0.00276263, -0.02383832, -0.99971201]
# #Translation from camera frame to imu frame, imu^T_cam
# extrinsicTranslation: !!opencv-matrix
#    rows: 3
#    cols: 1
#    dt: d
#    data: [-0.00004114, -0.00006057, 0.00002384]

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 9.8844229202616352e-01, -1.7247282793985447e-03,
       -1.5158779847476753e-01, 6.0624304285412023e-01,
       6.3507796006051932e-03, -9.9858636547618884e-01,
       5.2772514470321150e-02, 7.6079089856047921e+01,
       -1.5146452697753696e-01, -5.3125285857282323e-02,
       -9.8703404250818694e-01, 6.3040934043433498e-03, 0., 0., 0., 1. ]
       
#Multiple thread support
multiple_thread: 1


#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 25            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 1.6e-2          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 2.4e-3        # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 5.5e-4         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 2.0e-4         # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.806         # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 1        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/ocean/vins_fusion/vins_output/pose_graph/" # save and load path
save_image: 1 